

<body>
<!--Start Slider-->		<section class="title_page bg_3">			<div class="container">				<div class="row">					<div class="col-lg-12 col-md-12 col-sm-12">						<h2>About Us</h2>						<nav id="breadcrumbs">							<ul>								<li><a href="index.html">Home</a></li>								<li><a href="index.html">Pages</a></li>								<li>About Us</li>							</ul>						</nav>					</div>				</div>			</div>		</section>		<!--End Slider-->				<!-- Start ABout Page -->		<section class="content about_page">			<div class="container">				<div class="row">					<div class="col-lg-6 col-md-6 col-sm-6">						<div class="img-about">							<div id="about_slide" class="swipe">								<ul class="swipe-wrap">									<li><img src="img/about/1.jpg" alt="" /></li>									<li><img src="img/about/2.jpg" alt="" /></li>									<li><img src="img/about/3.jpg" alt="" /></li>								</ul>								<div class="swipe-navi">								  <div class="swipe-left" onClick="mySwipe.prev()"><i class="fa fa-chevron-left"></i></div> 								  <div class="swipe-right" onClick="mySwipe.next()"><i class="fa fa-chevron-right"></i></div>								</div>							</div>						</div>					</div>					<div class="col-lg-6 col-md-6 col-sm-6">						<div class="title_content">							<h3>Our History</h3>						</div>						<div class="our_history">							<p>Buddy Boy Technologies, (BBT) is a whole new level of integration and aptitude for people who want more than just an average run of the mill entertainment experience. Our products will REVOLUTIONIZE the way people view consumer electronics and entertainment, and will show consumers a new and fun way to intertwine learning with new technology and gaming. BBT is bringing new, fun, innovative technology to people who LOVE all kinds of movies, reading all different genres of books, video gaming and other entertainment.</p>
          <p>The first project of Buddy Boy Technologies is turning Tiffany&rsquo;s first book, &ldquo;The Pandora Affair&rdquo; into a video game. That&rsquo;s right, an adult romance video game! With interactive programming, you will not only enjoy the book, you will be able to make design, play and conquer your own alternate journey and destination ending. You will experience hands on feelings with remote controlled romance, sex, drama, action, thriller, suspense, murder and humor. Along with all Tiffany&rsquo;s literary creations, there will be many other Independent Authors who will be submitting their work for video game design as well.</p>
          <p>Along with the game developments, BBT is also creating standard and custom console boxes with high tech remotes, that allow further interaction with all the games.</p>
          <p>&nbsp;</p>
          <p>Tiffany Toto, Founder and CEO of Buddy Boy Technologies</p>
</div>					</div>				</div>				<div class="row">					<div class="col-lg-6 col-md-6 col-sm-6">						<div class="title_content">							<h3>How We Do?</h3>						</div>						<div class="how_do">							<!-- Tabs Navigation -->							<ul class="tabs-nav">								<li class="active"><a href="#tab1">Our Mission</a></li>								<li><a href="#tab2">Second</a></li>								<li><a href="#tab3"><i class="fa fa-comments"></i>Supports</a></li>							</ul>							<!-- Tabs Content -->							<div class="tabs-container">								<div class="tab-content" id="tab1">									<h4>&nbsp;</h4>									<p>BBT will be bringing books and educational importance back into technology, video gaming and entertainment.</p>
          <p>We will be your new generation, full service technology based entertainment aphrodisiac.</p>
          <p>We look forward to bringing you everything you ever wanted in a gaming experience!</p>
</div>								<div class="tab-content" id="tab2">									<h4>Consectetur adipisicing elit</h4>									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod									tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,									quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo									consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse									cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non									proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>								</div>								<div class="tab-content" id="tab3">									<h4>deserunt mollit anim</h4>									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod									tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,									quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo									consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse									cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non									proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>								</div>							</div>						</div>					</div>					<div class="col-lg-6 col-md-6 col-sm-6">						<div class="title_content">							<h3>Our Skills</h3>						</div>						<div class="our_skill">							<p>We believe in being up front and honest, and showing our skills as a company, NOT individuals</p>							<ul class="progress-skill-bar">								<li>									<span class="lable">70%</span>									<div class="progress_skill">										<div class="bar" data-value="70" role="progressbar" data-height="100">											HTML										</div>									</div>								</li>								<li>									<span class="lable">80%</span>									<div class="progress_skill">										<div class="bar" data-value="80" role="progressbar" data-height="100">											CSS										</div>									</div>								</li>								<li>									<span class="lable">100%</span>
              <div class="progress_skill">										<div class="bar" data-value="100" role="progressbar" data-height="100">	 Customer Satisfaction</div>									</div>								</li>								<li>									<span class="lable">80%</span>									<div class="progress_skill">										<div class="bar" data-value="80" role="progressbar" data-height="100">											MySQL										</div>									</div>								</li>								<li>									<span class="lable">70%</span>									<div class="progress_skill">										<div class="bar" data-value="70" role="progressbar" data-height="100">											PHP										</div>									</div>								</li>							</ul>						</div>					</div>				</div>			</div>		</section>		<!-- End About Page -->
</body>
</html>