

<body>
<!--START Meet Team-->		<section class="content bg_grey">			<div class="container">				<div class="row">					<div class="col-lg-12 col-md-12 col-sm-12" data-effect="slide-top">						<div class="title">							<h2>Meet our amazing team</h2>							<p>Nullam ut consectetur dolor. Sed sit amet iaculis nisi. Mauris ridiculus elementum non felis etewe blandit. Vestibulum iaculis dolor porttitors erte.</p>						</div>					</div>				</div>				<div class="row">					<div class="meet_team" data-effect="slide-bottom">						<ul class="team_slides">							<li>								<div class="team list_team" data-effect="slide-bottom">									<div class="content_team">										<img alt="" src="img/team/10384531_1467173890193013_1297861219611817288_n.jpg" width="465" height="300">										<div class="photo_hover">											<ul>												<li><a class="facebook" href="#" data-toggle="tooltip" title="Facebook" data-placement="right"><i class="fa fa-facebook"></i></a></li>												<li><a class="twitter" href="#"  data-toggle="tooltip" title="Twitter" data-placement="right"><i class="fa fa-twitter"></i></a></li>												<li><a class="linkedin" href="#" data-toggle="tooltip" title="Linkedin" data-placement="right"><i class="fa fa-linkedin"></i></a></li>											</ul>										</div>									</div>									<div class="team_detail">										<h5>Tiffany Toto </h5>
  Founder and Chief Executive Officer<br/><br/>
  <p>Tiffany Toto is the Founder and CEO of Buddy Boy Technologies, and she is responsible for providing strategic leadership for the company by working with other management to establish long-range goals, strategies, plans, and policies. She is a published romance author. </p>									
  </div>								</div>							</li>							<li>								<div class="team list_team" data-effect="slide-bottom">									<div class="content_team">										<img alt="" src="img/team/james.jpg" width="465" height="300">										<div class="photo_hover">											<ul>												<li><a class="facebook" href="#" data-toggle="tooltip" title="Facebook" data-placement="right"><i class="fa fa-facebook"></i></a></li>												<li><a class="twitter" href="#"  data-toggle="tooltip" title="Twitter" data-placement="right"><i class="fa fa-twitter"></i></a></li>												<li><a class="linkedin" href="#" data-toggle="tooltip" title="Linkedin" data-placement="right"><i class="fa fa-linkedin"></i></a></li>												<li><a class="pinterest" href="#" data-toggle="tooltip" title="Pinterest" data-placement="right"><i class="fa fa-pinterest"></i></a></li>											</ul>										</div>									</div>									<div class="team_detail">										<h5>James Gouine</h5>
        Director of Product Quality<br/><br/>
        <p>He has over 14 years of technology experience, including building computers, setting up and managing on site and remote networks. He was honorably discharged from the United States Air Force and also have a background in Military Law Enforcement. He is a avid gamer, and love new technology. He is a talent individual with a great eye for detail, with a very bubbly personality, who drives hard to ensure the highest possible standards with our products.</p>									
        </div>								</div>							</li>							<li>								<div class="team list_team" data-effect="slide-bottom">									<div class="content_team">										<img alt="" src="img/team/jules.jpg" width="465" height="300">										<div class="photo_hover">											<ul>												<li><a class="facebook" href="#" data-toggle="tooltip" title="Facebook" data-placement="right"><i class="fa fa-facebook"></i></a></li>												<li><a class="twitter" href="#"  data-toggle="tooltip" title="Twitter" data-placement="right"><i class="fa fa-twitter"></i></a></li>												<li><a class="google-plus" href="#" data-toggle="tooltip" title="Google+" data-placement="right"><i class="fa fa-google-plus"></i></a></li>												<li><a class="linkedin" href="#" data-toggle="tooltip" title="Linkedin" data-placement="right"><i class="fa fa-linkedin"></i></a></li>											</ul>										</div>									</div>									<div class="team_detail">										<h5>Jules Warner</h5>
                    Chief of Operations<br>
                    Lead Engineer<br>
                    Director of Creative Design<br/><br/>
                    Lead Project Manager
       <p>Julian has 12 years of technical experience, and 3 years engineering experience, including computer and laptop technician, technical support, customer services, building and developing websites.
       He is a qulified ONC E%E engineer, and despite his lack of qulaifications and experience, he is extremely creative, imaginative, inspiring, and extremely talented young man, he strives to get work done to an extermely high standards, and is very passionate about the work he does. 
        </div>								</div>							</li>							<li>								<div class="team list_team" data-effect="slide-bottom">									<div class="content_team">										<img alt="" src="" width="465" height="300">										<div class="photo_hover">											<ul>												<li><a class="facebook" href="#" data-toggle="tooltip" title="Facebook" data-placement="right"><i class="fa fa-facebook"></i></a></li>												<li><a class="twitter" href="#"  data-toggle="tooltip" title="Twitter" data-placement="right"><i class="fa fa-twitter"></i></a></li>												<li><a class="pinterest" href="#" data-toggle="tooltip" title="Pinterest" data-placement="right"><i class="fa fa-pinterest"></i></a></li>											</ul>										</div>									</div>									<div class="team_detail">										<h5></h5>
              
                    
                    
              </div>
              </div></li>
              <li>
                <div class="team list_team" data-effect="slide-bottom">
                  <div class="team_detail">
                    <p>.</p>									
                  </div>
                </div>
              </li>							
              <li>								<div class="team list_team" data-effect="slide-bottom">									<div class="content_team">										<img alt="" src="img/team/2.jpg">										<div class="photo_hover">											<ul>												<li><a class="facebook" href="#" data-toggle="tooltip" title="Facebook" data-placement="right"><i class="fa fa-facebook"></i></a></li>												<li><a class="twitter" href="#"  data-toggle="tooltip" title="Twitter" data-placement="right"><i class="fa fa-twitter"></i></a></li>												<li><a class="google-plus" href="#" data-toggle="tooltip" title="Google+" data-placement="right"><i class="fa fa-google-plus"></i></a></li>											</ul>										</div>									</div>									<div class="team_detail">										<h5>JHOEN DOE</h5>										<span class="jobs">Web Programmer</span>										<p>Dicant vocent nominavi ex namo dei, labora probatus neci, duo sonetawer vocent repre hendunt ei. Pondemerli reprimiue at glamr gamen nullam uti consectetur dolor parturient metasa.</p>									</div>								</div>							</li>							<li>								<div class="team list_team" data-effect="slide-bottom">									<div class="content_team">										<img alt="" src="img/team/3.jpg">										<div class="photo_hover">											<ul>												<li><a class="facebook" href="#" data-toggle="tooltip" title="Facebook" data-placement="right"><i class="fa fa-facebook"></i></a></li>												<li><a class="twitter" href="#"  data-toggle="tooltip" title="Twitter" data-placement="right"><i class="fa fa-twitter"></i></a></li>												<li><a class="linkedin" href="#" data-toggle="tooltip" title="Linkedin" data-placement="right"><i class="fa fa-linkedin"></i></a></li>											</ul>										</div>									</div>									<div class="team_detail">										<h5>JHOEN DOE</h5>										<span class="jobs">Web Programmer</span>										<p>Dicant vocent nominavi ex namo dei, labora probatus neci, duo sonetawer vocent repre hendunt ei. Pondemerli reprimiue at glamr gamen nullam uti consectetur dolor parturient metasa.</p>									</div>								</div>							</li>						</ul>					</div>				</div>			</div>		</section>		<!--End Meet Team-->
</body>
</html>